# -*- coding: utf-8 -*-
"""Energy EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gck1IttLjEECUJNUXjt1a4Oa0enRpPhk
"""

pip install squarify

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import missingno as msno
import squarify
import plotly.graph_objects as go
import plotly.express as px
import statsmodels.api as sm
import numpy as np
from statsmodels.tsa.seasonal import seasonal_decompose
plt.rcParams.update({'figure.autolayout': True})

df = pd.read_csv('final_padv.csv')

print("Dataset shape:", df.shape)
print("\nDataset info:")
df.info()
print("\nFirst 5 rows:")
display(df.head())

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print("\nNumeric summary:")
display(df[numeric_cols].describe())

# Count and percentage of missing values
missing_counts = df.isnull().sum()
missing_percent = (missing_counts / len(df)) * 100
missing_df = pd.DataFrame({'Missing Count': missing_counts, 'Missing %': missing_percent})
missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False)

if missing_df.empty:
    print("✅ No missing values found in the dataset!")
else:
    display(missing_df)

    # Bar Chart of Missing Percentages
    plt.figure(figsize=(10, 6))
    sns.barplot(x=missing_df['Missing %'], y=missing_df.index, palette='mako')
    plt.title("Percentage of Missing Values per Column", fontsize=14)
    plt.xlabel("Missing Percentage (%)")
    plt.ylabel("Column Name")
    plt.tight_layout()
    plt.show()

    # Dendrogram of Missing Data Correlations
    plt.figure(figsize=(10, 4))
    msno.dendrogram(df)
    plt.title("Missing Data Correlation Dendrogram", fontsize=14)
    plt.show()

skew_values = df[numeric_cols].skew()
kurt_values = df[numeric_cols].kurtosis()

# Skewness
plt.figure(figsize=(max(8, len(skew_values)*0.6), 5))
plt.stem(skew_values.index, skew_values.values, basefmt=" ")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Skewness")
plt.title("Skewness of Numeric Columns (Lollipop Chart)")
plt.tight_layout()
plt.show()

# Kurtosis
plt.figure(figsize=(max(8, len(kurt_values)*0.6), 5))
plt.stem(kurt_values.index, kurt_values.values, basefmt=" ")
plt.xticks(rotation=45, ha='right')
plt.ylabel("Kurtosis")
plt.title("Kurtosis of Numeric Columns (Lollipop Chart)")
plt.tight_layout()
plt.show()

num_cols = len(numeric_cols)
rows = math.ceil(num_cols / 5)
plt.figure(figsize=(20, rows * 3.5))

for i, col in enumerate(numeric_cols):
    plt.subplot(rows, 5, i + 1)
    sns.violinplot(y=df[col], color='skyblue')
    plt.title(f"{col}\nSkew: {df[col].skew():.2f}", fontsize=10)
    plt.xlabel('')
    plt.ylabel('')
    plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

exclude_cols = ['Building Name', 'Montgomery County Building ID', 'Address', 'State']

for col in categorical_cols:
    if col in exclude_cols:
        continue

    print(f"\n🧩 Analyzing column: {col}")
    value_counts = df[col].value_counts(dropna=False)
    unique_count = len(value_counts)
    top_n = 10 if unique_count > 15 else unique_count
    top_values = value_counts.nlargest(top_n)
    if unique_count > top_n:
        top_values.loc['Others'] = value_counts.iloc[top_n:].sum()

    plt.figure(figsize=(8, max(5, top_n * 0.5)))
    sns.barplot(x=top_values.values, y=top_values.index, palette='viridis')
    plt.title(f"Top {top_n} Categories in {col}", fontsize=12)
    plt.xlabel("Count")
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

top_types = df.groupby('Primary Property Type Self Selected')['Total GHG Emissions (Metric Tons CO2e)'].sum().sort_values(ascending=False).head(15)

plt.figure(figsize=(12, 7))
colors = sns.color_palette('Spectral', len(top_types))
squarify.plot(
    sizes=top_types.values,
    label=[f"{label}\n{value:.0f} MTCO₂e" for label, value in zip(top_types.index, top_types.values)],
    color=colors,
    alpha=0.85
)
plt.title('Total GHG Emissions by Property Type (Top 15)', fontsize=16, fontweight='bold')
plt.axis('off')
plt.show()

avg_scores = df.groupby(['Primary Property Type Self Selected','Year'])['ENERGY STAR Score'].mean().unstack().dropna()

fig = go.Figure()
for idx, row in avg_scores.iterrows():
    fig.add_trace(go.Scatter(x=[2023,2024], y=[row[2023], row[2024]], mode='lines+markers', marker=dict(size=12), name=idx))

fig.update_layout(title='ENERGY STAR Score Change 2023 → 2024 by Property Type',
                  xaxis_title='Year', yaxis_title='Average ENERGY STAR Score')
fig.show()

top_ghg = df.nlargest(10,'Total GHG Emissions (Metric Tons CO2e)')

fig = go.Figure(go.Waterfall(
    name="GHG Contribution",
    orientation="v",
    measure=["relative"]*10,
    x=top_ghg['Building Name'],
    y=top_ghg['Total GHG Emissions (Metric Tons CO2e)'],
    text=[f"{v:.0f}" for v in top_ghg['Total GHG Emissions (Metric Tons CO2e)']],
    textposition="outside"
))
fig.update_layout(title="Waterfall: Top 10 Buildings by Total GHG Emissions", waterfallgroupgap = 0.5)
fig.show()

plt.figure(figsize=(14,6))
sns.violinplot(data=df, x='Primary Property Type Self Selected', y='Site EUI', palette='Set2')
plt.xticks(rotation=90)
plt.title('Distribution of Site EUI by Property Type', fontsize=16)
plt.ylabel('Site EUI')
plt.xlabel('Property Type')
plt.show()

import plotly.express as px
import pandas as pd

# Drop rows with missing values
df_subset = df.dropna(subset=[
    'Electricity (kWh)',
    'Natural Gas (therms)',
    'Site EUI',
    'Total GHG Emissions (Metric Tons CO2e)',
    'Primary Property Type Self Selected'
]).copy()

# 🧹 Keep only the top 10 property types by frequency for clarity
top_types = df_subset['Primary Property Type Self Selected'].value_counts().nlargest(10).index
df_subset = df_subset[df_subset['Primary Property Type Self Selected'].isin(top_types)]

# Encode property types numerically
df_subset['Primary Property Type Self Selected_numeric'], uniques = pd.factorize(df_subset['Primary Property Type Self Selected'])

# Create mapping dictionary
mapping = dict(enumerate(uniques))
print("🎨 Color Mapping (Numeric → Property Type):")
for num, prop in mapping.items():
    print(f"{num}: {prop}")

# Create the parallel coordinates plot
fig = px.parallel_coordinates(
    df_subset,
    dimensions=['Electricity (kWh)', 'Natural Gas (therms)', 'Site EUI', 'Total GHG Emissions (Metric Tons CO2e)'],
    color='Primary Property Type Self Selected_numeric',
    color_continuous_scale=px.colors.sequential.Viridis,
    title='Parallel Coordinates: Multi-metric Comparison by Top 10 Property Types',
)

# Add labeled color bar with only top 10 property types
fig.update_layout(
    coloraxis_colorbar=dict(
        title='Property Type',
        tickvals=list(mapping.keys()),
        ticktext=list(mapping.values())
    )
)

fig.show()

# For simplicity, using city centroids
city_summary = df.groupby('City').agg({'Total GHG Emissions (Metric Tons CO2e)':'sum',
                                       'Electricity (kWh)':'sum'}).reset_index()

# Sort city_summary by 'Total GHG Emissions (Metric Tons CO2e)' in descending order
city_summary = city_summary.sort_values(by='Total GHG Emissions (Metric Tons CO2e)', ascending=False)

# Add approximate lat/lon for the top cities manually
# Ensure the number of coordinates matches the number of cities you are including
city_summary = city_summary.head(4).copy() # Take the top 4 cities

city_summary['lat'] = [39.083, 38.990, 39.143, 38.980]  # Example lat for the top 4 cities
city_summary['lon'] = [-77.152, -77.026, -77.201, -77.099] # Example lon for the top 4 cities


fig = px.scatter_mapbox(city_summary, lat='lat', lon='lon', size='Total GHG Emissions (Metric Tons CO2e)',
                        hover_name='City', hover_data=['Electricity (kWh)'],
                        color='Total GHG Emissions (Metric Tons CO2e)',
                        size_max=50, zoom=9, mapbox_style='carto-positron',
                        title='City-wise Total GHG Emissions (Top 4 Cities)')
fig.show()

df_renamed = df.rename(columns={
    'Electricity (kWh)': 'Electricity',
    'Natural Gas (therms)': 'Gas',
    'Total GHG Emissions (Metric Tons CO2e)': 'Total GHG',
    'Direct GHG Emissions (Metric Tons CO2e)': 'Direct GHG'
})

numeric_cols = ['Electricity','Gas','Site EUI','Total GHG','Direct GHG']

fig = px.scatter_matrix(
    df_renamed,
    dimensions=numeric_cols,
    color='Primary Property Type Self Selected',
    hover_name='Building Name',
    title='Pair Plot: Multi-variable Correlations'
)

fig.update_layout(width=1200, height=1200)
fig.show()

# 1️⃣ Identify top 5 property types by total GHG emissions
top_props = df.groupby('Primary Property Type Self Selected')['Total GHG Emissions (Metric Tons CO2e)'].sum() \
              .sort_values(ascending=False).head(5).index.tolist()

# 2️⃣ Aggregate data for these top property types
agg_data = []
for prop in top_props:
    subset = df[df['Primary Property Type Self Selected'] == prop]
    elec_sum = subset['Electricity (kWh)'].sum()
    gas_sum = subset['Natural Gas (therms)'].sum()
    total_ghg = subset['Total GHG Emissions (Metric Tons CO2e)'].sum()
    agg_data.append({'Property': prop, 'Electricity': elec_sum, 'Natural Gas': gas_sum, 'Total_GHG': total_ghg})

agg_df = pd.DataFrame(agg_data)

# 3️⃣ Prepare nodes and links
labels = ['Electricity', 'Natural Gas'] + top_props + ['Total GHG Emissions']

source = []
target = []
value = []

# Link energy → property types
for i, prop in enumerate(top_props):
    source.append(0)  # Electricity
    target.append(2 + i)  # Property
    value.append(agg_df.loc[i, 'Electricity'])

    source.append(1)  # Natural Gas
    target.append(2 + i)  # Property
    value.append(agg_df.loc[i, 'Natural Gas'])

# Link property types → Total GHG
for i, prop in enumerate(top_props):
    source.append(2 + i)  # Property
    target.append(len(labels)-1)  # Total GHG
    value.append(agg_df.loc[i, 'Total_GHG'])

# 4️⃣ Create Sankey diagram
fig = go.Figure(data=[go.Sankey(
    node=dict(
        label=labels,
        pad=15,
        thickness=20,
        color=['skyblue', 'orange'] + ['lightgreen']*len(top_props) + ['red']
    ),
    link=dict(
        source=source,
        target=target,
        value=value,
        color=['rgba(0,0,255,0.5)' if s==0 else 'rgba(255,165,0,0.5)' for s in source]
    )
)])

fig.update_layout(title_text="Energy → Top 5 Property Types → Total GHG Emissions", font_size=12)
fig.show()

prop_energy = df.groupby(['Year','Primary Property Type Self Selected'])['Electricity (kWh)'].sum().reset_index()
fig = px.area(prop_energy, x='Year', y='Electricity (kWh)', color='Primary Property Type Self Selected',
              hover_name='Primary Property Type Self Selected',
              title='Electricity Use by Property Type Over Years',
              color_discrete_sequence=px.colors.sequential.Plasma)
fig.show()

fig = px.box(df, x='Primary Property Type Self Selected', y='Site EUI',
             color='Primary Property Type Self Selected',
             title='Box Plot: Distribution of Site EUI by Property Type')
fig.update_layout(xaxis_tickangle=-45)
fig.show()

# Aggregate yearly Site EUI
ts = df.groupby('Year')['Site EUI'].mean()
ts.index = pd.to_datetime(ts.index.astype(str))  # convert years to datetime

# Decompose the series (trend + residual only, since annual)
result = seasonal_decompose(ts, model='additive', period=1)

# Plotting a clean figure
fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)

axes[0].plot(ts, label='Original', marker='o')
axes[0].set_ylabel('Site EUI')
axes[0].set_title('Original Site EUI per Year')
axes[0].legend()

axes[1].plot(result.trend, color='green', marker='o')
axes[1].set_ylabel('Trend')
axes[1].set_title('Trend Component')

axes[2].plot(result.resid, color='red', marker='o')
axes[2].set_ylabel('Residual')
axes[2].set_title('Residual Component')
axes[2].set_xlabel('Year')

plt.tight_layout()
plt.show()

trend_df = df.groupby(['Year','Primary Property Type Self Selected'])['Site EUI'].mean().reset_index()

fig = px.line(trend_df, x='Year', y='Site EUI', color='Primary Property Type Self Selected',
              markers=True,
              title='Trend & Rate of Change: Site EUI Over Years')

# Slider to select year range
fig.update_layout(
    xaxis=dict(rangeslider=dict(visible=True)),
    yaxis_title='Average Site EUI',
    xaxis_title='Year'
)
fig.show()

fig = px.scatter(df.dropna(subset=['Total GHG Emissions (Metric Tons CO2e)']), x='Electricity (kWh)', y='Site EUI',
                 color='Primary Property Type Self Selected',
                 size='Total GHG Emissions (Metric Tons CO2e)',
                 hover_name='Building Name',
                 title='Dot Plot: Electricity vs Site EUI')
fig.show()

heatmap_df = df.groupby(['Year','Primary Property Type Self Selected'])['Site EUI'].mean().reset_index()
heatmap_matrix = heatmap_df.pivot(index='Primary Property Type Self Selected', columns='Year', values='Site EUI')

fig = px.imshow(heatmap_matrix, text_auto=True, color_continuous_scale='Viridis', title='Heatmap: Site EUI Trend & Variability')
fig.show()

# Predict Site EUI based on Electricity
X = df['Electricity (kWh)'].fillna(0)
y = df['Site EUI'].fillna(0)
X = sm.add_constant(X)  # add intercept

model = sm.OLS(y, X).fit()
print(model.summary())


fig = go.Figure()
fig.add_trace(go.Scatter(x=df['Electricity (kWh)'], y=df['Site EUI'], mode='markers', name='Data'))
fig.add_trace(go.Scatter(x=df['Electricity (kWh)'], y=model.predict(X), mode='lines', name='Least Squares Fit'))
fig.update_layout(title='Site EUI vs Electricity with Least Squares Trend Line', xaxis_title='Electricity (kWh)', yaxis_title='Site EUI')
fig.show()

plt.figure(figsize=(10,6))
sns.histplot(df['ENERGY STAR Score'], bins=20, kde=True, color='teal')
plt.title('Distribution of ENERGY STAR Scores', fontsize=16)
plt.xlabel('ENERGY STAR Score')
plt.ylabel('Count')
plt.show()

fig = px.scatter(
    df.dropna(subset=['Total GHG Emissions (Metric Tons CO2e)']),
    x='Electricity (kWh)',
    y='Site EUI',
    size='Total GHG Emissions (Metric Tons CO2e)',
    color='Primary Property Type Self Selected',
    animation_frame='Year',
    hover_name='Building Name',
    title='Animated Bubble Plot: Electricity vs Site EUI Over Years',
    size_max=60
)
fig.show()

numeric_cols_for_corr = df.select_dtypes(include=np.number).columns.tolist()

plt.figure(figsize=(12,8))
sns.heatmap(df[numeric_cols_for_corr].corr(), annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Matrix of Numeric Features")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Train the model
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("Mean Absolute Error (MAE):", mae)
print("R-squared (R²):", r2)

# Scatter plot of actual vs predicted
plt.figure(figsize=(6,4))
sns.scatterplot(x=y_test, y=y_pred)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')  # perfect prediction line
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title('Actual vs Predicted')
plt.show()

# Residual plot
residuals = y_test - y_pred
plt.figure(figsize=(6,4))
sns.histplot(residuals, kde=True)
plt.xlabel('Residuals')
plt.title('Residual Distribution')
plt.show()

# Define absolute error
errors = np.abs(y_test - y_pred)

# Choose thresholds
thresholds = np.linspace(0, errors.max(), 100)

# Compute "True Positive Rate" as fraction of predictions within threshold
tpr = [(errors <= t).mean() for t in thresholds]

plt.figure(figsize=(6,4))
plt.plot(thresholds, tpr, label='Fraction of predictions within error threshold')
plt.xlabel('Error Threshold')
plt.ylabel('Fraction of predictions ≤ threshold')
plt.title('Regression Threshold Curve')
plt.legend()
plt.show()

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Read the dataset
df = pd.read_csv("final_padv.csv")

# Display column names to verify available features
print("Columns available in dataset:")
print(df.columns.tolist())

# Choose a categorical column for visualization
column = 'Primary Property Type Self Selected'

# Drop NaN or blank values for cleaner plots
data = df[column].dropna()

# Count frequencies of each category
counts = data.value_counts()

# Optionally restrict to top N categories for clarity
counts = counts.head(10)

# ---------------- PIE CHART ----------------
plt.figure(figsize=(8, 8))
plt.pie(
    counts,
    labels=counts.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=plt.cm.Paired.colors
)
plt.title(f"Distribution of {column} (Top 10 Categories) - Pie Chart", fontsize=14)
plt.tight_layout()
plt.show()

# ---------------- DONUT CHART ----------------
plt.figure(figsize=(8, 8))
wedges, texts, autotexts = plt.pie(
    counts,
    labels=counts.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=plt.cm.Set3.colors
)

# Add a white circle in the center to make it a donut chart
centre_circle = plt.Circle((0, 0), 0.70, fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

plt.title(f"Distribution of {column} (Top 10 Categories) - Donut Chart", fontsize=14)
plt.tight_layout()
plt.show()

df_scores = pd.DataFrame({'y_true': y_test, 'y_score': y_pred})
df_scores = df_scores.sort_values(by='y_score', ascending=False)
df_scores['decile'] = pd.qcut(df_scores['y_score'], 10, labels=False)

gain_chart = df_scores.groupby('decile')['y_true'].sum().cumsum()
lift_chart = gain_chart / gain_chart.max()

plt.figure(figsize=(8,5))
plt.plot(range(1,11), gain_chart, marker='o', label='Gain Chart')
plt.plot(range(1,11), lift_chart, marker='o', label='Lift Chart')
plt.xlabel('Decile')
plt.ylabel('Cumulative Gain / Lift')
plt.title('Gain & Lift Chart')
plt.legend()
plt.show()

# Use Seaborn style for cleaner visuals
sns.set_style("whitegrid")
plt.rcParams.update({'font.size': 11})

# Define color palette
colors = sns.color_palette("tab10", 4)

# Prepare figure
fig, axes = plt.subplots(2, 2, figsize=(16, 10))

# -----------------------------
# 1️⃣ Average Energy Metrics Over Time
# -----------------------------
yearly_metrics = df.groupby('Year').agg({
    'Site EUI': 'mean',
    'ENERGY STAR Score': 'mean',
    'Total GHG Emissions (Metric Tons CO2e)': 'mean'
}).dropna()

ax = axes[0, 0]
for i, metric in enumerate(yearly_metrics.columns):
    ax.plot(yearly_metrics.index, yearly_metrics[metric], marker='o', label=metric, color=colors[i])
ax.set_xlabel('Year')
ax.set_ylabel('Average Value')
ax.set_title('Average Energy Metrics Over Time')
ax.legend()
ax.grid(True, alpha=0.3)

# -----------------------------
# 2️⃣ Number of Buildings Reporting
# -----------------------------
ax = axes[0, 1]
buildings_per_year = df['Year'].value_counts().sort_index()
sns.barplot(x=buildings_per_year.index, y=buildings_per_year.values, hue=buildings_per_year.index, palette=colors[:len(buildings_per_year)], ax=ax, legend=False)
ax.set_xlabel('Year')
ax.set_ylabel('Number of Buildings')
ax.set_title('Buildings Reporting by Year')

# -----------------------------
# 3️⃣ Compliance Rate Over Time
# -----------------------------
ax = axes[1, 0]
compliance_by_year = df.groupby('Year')['Benchmarking Report Status'].value_counts().unstack().fillna(0)
if 'in compliance' in compliance_by_year.columns:
    compliance_rate = (compliance_by_year['in compliance'] / compliance_by_year.sum(axis=1)) * 100
    ax.plot(compliance_rate.index, compliance_rate.values, marker='o', color=colors[0])
    ax.set_ylabel('Compliance Rate (%)')
    ax.set_xlabel('Year')
    ax.set_title('Compliance Rate Over Time')
    ax.set_ylim(0, 105)
    ax.grid(True, alpha=0.3)
else:
    ax.text(0.5, 0.5, "No compliance data available", ha='center', va='center', fontsize=12)
    ax.axis('off')

# -----------------------------
# 4️⃣ Average Onsite Renewable Electricity Over Time
# -----------------------------
ax = axes[1, 1]
if 'Electricity Use Onsite Renewable (kWh)' in df.columns:
    renewable_by_year = df.groupby('Year')['Electricity Use Onsite Renewable (kWh)'].mean()
    ax.plot(renewable_by_year.index, renewable_by_year.values, marker='o', color='green')
    ax.set_ylabel('Average Renewable Electricity (kWh)')
    ax.set_xlabel('Year')
    ax.set_title('Onsite Renewable Electricity Over Time')
    ax.grid(True, alpha=0.3)
else:
    ax.text(0.5, 0.5, "No renewable data available", ha='center', va='center', fontsize=12)
    ax.axis('off')

plt.tight_layout()
plt.show()

import pandas as pd
import plotly.graph_objects as go
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# 🔹 Read your CSV file (make sure the path and name are correct)
data = pd.read_csv("final_padv.csv")  # change this if your file name is different

# 🔹 Select the 3 columns you want to plot
cols = ['Electricity (kWh)', 'Natural Gas (therms)', 'Weather-Normalized Site EUI']

# 🔹 Drop rows with NaN values in the selected columns
data_cleaned = data.dropna(subset=cols).copy()

# 🔹 Scale the cleaned data
scaled = StandardScaler().fit_transform(data_cleaned[cols])

# 🔹 Apply K-Means clustering to the scaled data
kmeans = KMeans(n_clusters=3, n_init=10, random_state=42)
clusters = kmeans.fit_predict(scaled)

# 🔹 Add the cluster labels to the cleaned DataFrame
data_cleaned['cluster'] = clusters

# 🔹 Merge the cluster labels back into the original DataFrame
data = data.merge(data_cleaned[['cluster']], left_index=True, right_index=True, how='left')


# 🔹 Create 3D Scatter Plot
fig = go.Figure(data=[
    go.Scatter3d(
        x=data[cols[0]],
        y=data[cols[1]],
        z=data[cols[2]],
        mode='markers',
        marker=dict(
            size=4,
            color=data['cluster'],
            colorscale='Viridis'
        )
    )
])

fig.update_layout(
    scene=dict(
        xaxis_title=cols[0],
        yaxis_title=cols[1],
        zaxis_title=cols[2]
    ),
    template="plotly_dark",
    height=700
)

# 🔹 Show the interactive 3D plot
fig.show()

# 9. KEY INSIGHTS AND SUMMARY
print("KEY INSIGHTS AND SUMMARY")
print("=" * 50)
energy_df = df[df['Site EUI'].notna()]
# Overall statistics
total_buildings = len(df)
buildings_with_energy_data = len(energy_df)
compliance_rate = (df['Benchmarking Report Status'] == 'in compliance').mean() * 100

print(f"Total buildings in dataset: {total_buildings}")
print(f"Buildings with complete energy data: {buildings_with_energy_data}")
print(f"Overall compliance rate: {compliance_rate:.1f}%")

# Top performing buildings
if 'ENERGY STAR Score' in energy_df.columns:
    top_performers = energy_df.nlargest(5, 'ENERGY STAR Score')[['Building Name', 'ENERGY STAR Score', 'Primary Property Type Self Selected']]
    print("\nTop 5 Performing Buildings (Highest ENERGY STAR Score):")
    print(top_performers.to_string(index=False))

# Most efficient buildings by EUI
most_efficient = energy_df.nsmallest(5, 'Site EUI')[['Building Name', 'Site EUI', 'Primary Property Type Self Selected']]
print("\nTop 5 Most Energy Efficient Buildings (Lowest Site EUI):")
print(most_efficient.to_string(index=False))

# Highest emitters
highest_emitters = energy_df.nlargest(5, 'Total GHG Emissions (Metric Tons CO2e)')[['Building Name', 'Total GHG Emissions (Metric Tons CO2e)', 'Primary Property Type Self Selected']]
print("\nTop 5 Highest GHG Emitters:")
print(highest_emitters.to_string(index=False))

# Property type analysis
print("\nProperty Type Energy Performance Summary:")
property_summary = energy_df.groupby('Primary Property Type Self Selected').agg({
    'Site EUI': ['count', 'mean', 'median', 'std'],
    'ENERGY STAR Score': 'mean',
    'Total GHG Emissions (Metric Tons CO2e)': 'mean'
}).round(2)

# Filter for property types with sufficient data
property_summary = property_summary[property_summary[('Site EUI', 'count')] >= 5]
print(property_summary.sort_values(('Site EUI', 'mean'), ascending=True).head(10))

from math import pi

def normalize_data(series):
    return (series - series.min()) / (series.max() - series.min())

# Define groups and metrics to compare
groups = df['Benchmarking Group'].unique()
metrics_to_compare = ['ENERGY STAR Score', 'Site EUI', 'Source EUI', 'Total GHG Emissions (Metric Tons CO2e)']
colors = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D'] # Define colors as well

# Normalize
normalized_data = []
for group in groups:
    group_metrics = df[df['Benchmarking Group'] == group][metrics_to_compare].mean()
    normalized_metrics = normalize_data(group_metrics)
    for metric in metrics_to_compare:
        normalized_data.append({
            'Group': group,
            'Metric': metric,
            'Normalized Value': normalized_metrics[metric]
        })

norm_df = pd.DataFrame(normalized_data)

# Plot Radar Chart
angles = np.linspace(0, 2*np.pi, len(metrics_to_compare), endpoint=False).tolist()
angles += angles[:1]  # complete circle

fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))

for i, group in enumerate(groups):
    group_norm = norm_df[norm_df['Group'] == group]
    values = group_norm['Normalized Value'].tolist()
    values += values[:1]
    ax.plot(angles, values, 'o-', linewidth=2, label=group, color=colors[i])
    ax.fill(angles, values, alpha=0.2, color=colors[i])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(metrics_to_compare)
ax.set_ylim(0, 1)
ax.set_title('Normalized Metrics Comparison (Radar Chart - Full Dataset)',
             fontweight='bold', fontsize=14)
ax.legend(loc='upper right')
plt.show()

# Comprehensive Multiple Metrics Analysis: Full Dataset Only
fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# Plot 1: Multiple Metrics Comparison by Group (Full Dataset)
metrics_to_compare = ['ENERGY STAR Score', 'Site EUI', 'Source EUI', 'Total GHG Emissions (Metric Tons CO2e)']
comparison_data = []

for metric in metrics_to_compare:
    full_dataset_mean = df.groupby('Benchmarking Group')[metric].mean()

    for group in full_dataset_mean.index:
        comparison_data.append({
            'Metric': metric,
            'Benchmarking Group': group,
            'Full Dataset': full_dataset_mean[group]
        })

comparison_df = pd.DataFrame(comparison_data)

# Create grouped bar chart for multiple metrics
x_pos = np.arange(len(metrics_to_compare))
width = 0.6
groups = comparison_df['Benchmarking Group'].unique()
colors = ['#2E86AB', '#A23B72', '#F18F01', '#C73E1D']

for i, group in enumerate(groups):
    group_data = comparison_df[comparison_df['Benchmarking Group'] == group]
    bars = axes[0,0].bar(x_pos + i*width/len(groups), group_data['Full Dataset'],
                        width/len(groups), label=group, alpha=0.8, color=colors[i])

    # Add value labels on bars
    for j, bar in enumerate(bars):
        height = bar.get_height()
        axes[0,0].text(bar.get_x() + bar.get_width()/2., height + height*0.01,
                      f'{height:.1f}', ha='center', va='bottom', fontweight='bold', fontsize=9)

axes[0,0].set_xlabel('Performance Metrics', fontsize=12, fontweight='bold')
axes[0,0].set_ylabel('Average Values', fontsize=12, fontweight='bold')
axes[0,0].set_title('Multiple Metrics Comparison by Benchmarking Group\n(Full Dataset)',
                   fontsize=14, fontweight='bold', pad=20)
axes[0,0].set_xticks(x_pos + width/2)
axes[0,0].set_xticklabels(metrics_to_compare, rotation=45)
axes[0,0].legend(title='Benchmarking Group', title_fontsize=12)
axes[0,0].grid(True, alpha=0.3, axis='y')

# Plot 2: Radar Chart - Normalized Metrics (Full Dataset)
from math import pi

# Normalize data for radar chart
def normalize_data(series):
    return (series - series.min()) / (series.max() - series.min())

normalized_data = []
for group in groups:
    group_metrics = df[df['Benchmarking Group'] == group][metrics_to_compare].mean()
    normalized_metrics = normalize_data(group_metrics)

    for metric in metrics_to_compare:
        normalized_data.append({
            'Group': group,
            'Metric': metric,
            'Normalized Value': normalized_metrics[metric]
        })

norm_df = pd.DataFrame(normalized_data)

# Create radar-style visualization
angles = np.linspace(0, 2*np.pi, len(metrics_to_compare), endpoint=False).tolist()
angles += angles[:1]  # Complete the circle

for i, group in enumerate(groups):
    group_norm = norm_df[norm_df['Group'] == group]
    values = group_norm['Normalized Value'].tolist()
    values += values[:1]  # Complete the circle

    axes[0,1].plot(angles, values, 'o-', linewidth=3, label=group,
                  color=colors[i], markersize=8)
    axes[0,1].fill(angles, values, alpha=0.2, color=colors[i])

axes[0,1].set_xticks(angles[:-1])
axes[0,1].set_xticklabels(metrics_to_compare, fontsize=10)
axes[0,1].set_ylim(0, 1)
axes[0,1].set_yticks([0, 0.2, 0.4, 0.6, 0.8, 1.0])
axes[0,1].set_title('Normalized Metrics Comparison\n(Radar Chart - Full Dataset)',
                   fontweight='bold', fontsize=14)
axes[0,1].legend(bbox_to_anchor=(1.15, 1), loc='upper left', fontsize=10)
axes[0,1].grid(True, alpha=0.3)

# Add value labels on radar chart points
for i, group in enumerate(groups):
    group_norm = norm_df[norm_df['Group'] == group]
    values = group_norm['Normalized Value'].tolist()
    values += values[:1]

    for j, (angle, value) in enumerate(zip(angles[:-1], values[:-1])):
        axes[0,1].text(angle, value + 0.05, f'{value:.2f}',
                      ha='center', va='center', fontsize=8, fontweight='bold',
                      bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.8))

# Plot 3: Box Plot Distribution Analysis
boxplot_data = []
for metric in ['ENERGY STAR Score', 'Site EUI']:
    for group in groups:
        values = df[df['Benchmarking Group'] == group][metric].dropna()
        for val in values:
            boxplot_data.append({
                'Metric': metric,
                'Benchmarking Group': group,
                'Value': val
            })

boxplot_df = pd.DataFrame(boxplot_data)

# Create box plots
sns.boxplot(data=boxplot_df[boxplot_df['Metric'] == 'ENERGY STAR Score'],
            x='Benchmarking Group', y='Value', ax=axes[1,0], palette=colors)
axes[1,0].set_title('ENERGY STAR Score Distribution by Group\n(Full Dataset)',
                   fontweight='bold', fontsize=12)
axes[1,0].set_ylabel('ENERGY STAR Score', fontweight='bold')
axes[1,0].set_xlabel('Benchmarking Group', fontweight='bold')
axes[1,0].tick_params(axis='x', rotation=45)

sns.boxplot(data=boxplot_df[boxplot_df['Metric'] == 'Site EUI'],
            x='Benchmarking Group', y='Value', ax=axes[1,1], palette=colors)
axes[1,1].set_title('Site EUI Distribution by Group\n(Full Dataset)',
                   fontweight='bold', fontsize=12)
axes[1,1].set_ylabel('Site EUI', fontweight='bold')
axes[1,1].set_xlabel('Benchmarking Group', fontweight='bold')
axes[1,1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Plot 4: Stacked Bar Chart - Performance Metrics Distribution
fig, ax = plt.subplots(figsize=(14, 8))

# Calculate percentage distribution for each metric
stacked_data = []
for metric in metrics_to_compare:
    metric_totals = df.groupby('Benchmarking Group')[metric].sum()
    total_metric = metric_totals.sum()

    for group in groups:
        percentage = (metric_totals[group] / total_metric) * 100
        stacked_data.append({
            'Metric': metric,
            'Benchmarking Group': group,
            'Percentage': percentage
        })

stacked_df = pd.DataFrame(stacked_data)
pivot_stacked = stacked_df.pivot(index='Metric', columns='Benchmarking Group', values='Percentage')

# Create stacked bar chart
pivot_stacked.plot(kind='bar', stacked=True, ax=ax, color=colors, alpha=0.8,
                   edgecolor='black', linewidth=0.5)

ax.set_xlabel('Performance Metrics', fontsize=12, fontweight='bold')
ax.set_ylabel('Percentage Distribution (%)', fontsize=12, fontweight='bold')
ax.set_title('Percentage Distribution of Metrics Across Benchmarking Groups\n(Full Dataset)',
            fontsize=14, fontweight='bold', pad=20)
ax.legend(title='Benchmarking Group', title_fontsize=12, bbox_to_anchor=(1.05, 1), loc='upper left')
ax.grid(True, alpha=0.3, axis='y')
ax.tick_params(axis='x', rotation=45)

# Add percentage labels
for container in ax.containers:
    ax.bar_label(container, labels=[f'{v:.1f}%' if v > 5 else '' for v in container.datavalues],
                fontsize=8, fontweight='bold')

plt.tight_layout()
plt.show()

# Plot 5: Performance Ranking Heatmap
fig, ax = plt.subplots(figsize=(12, 8))

# Calculate rankings for each metric
ranking_data = []
for metric in metrics_to_compare:
    group_means = df.groupby('Benchmarking Group')[metric].mean()
    # For ENERGY STAR Score, higher is better; for others, lower is better
    if metric == 'ENERGY STAR Score':
        rankings = group_means.rank(ascending=False)
    else:
        rankings = group_means.rank(ascending=True)

    for group in groups:
        ranking_data.append({
            'Metric': metric,
            'Benchmarking Group': group,
            'Rank': rankings[group],
            'Actual Value': group_means[group]
        })

ranking_df = pd.DataFrame(ranking_data)
pivot_rank = ranking_df.pivot(index='Benchmarking Group', columns='Metric', values='Rank')

# Create ranking heatmap
sns.heatmap(pivot_rank, annot=True, cmap='YlGnBu_r', ax=ax,
            fmt='.0f', cbar_kws={'label': 'Rank (1 = Best)'},
            linewidths=0.5, linecolor='white')

ax.set_title('Performance Ranking Heatmap\n(1 = Best Performance, 4 = Worst)\nFull Dataset',
            fontweight='bold', fontsize=14, pad=20)

# Add actual values as secondary annotation
for i in range(len(pivot_rank)):
    for j in range(len(pivot_rank.columns)):
        group = pivot_rank.index[i]
        metric = pivot_rank.columns[j]
        actual_value = ranking_df[(ranking_df['Benchmarking Group'] == group) &
                                (ranking_df['Metric'] == metric)]['Actual Value'].values[0]
        ax.text(j + 0.5, i + 0.7, f'({actual_value:.1f})',
                ha='center', va='center', fontsize=8, fontweight='bold',
                bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.7))

plt.tight_layout()
plt.show()

# Statistical Summary
print("\n" + "="*70)
print("COMPREHENSIVE MULTI-METRIC ANALYSIS - FULL DATASET")
print("="*70)

print("\n1. PERFORMANCE SUMMARY BY GROUP:")
performance_summary = df.groupby('Benchmarking Group')[metrics_to_compare].agg(['mean', 'std'])
print(performance_summary.round(2))

print("\n2. KEY INSIGHTS:")
print("• Group-level performance patterns across multiple energy metrics")
print("• Normalized comparison reveals relative strengths and weaknesses")
print("• Distribution analysis shows variability within each group")
print("• Ranking system identifies top performers for each metric")
print("• Percentage distribution highlights group contributions to total metrics")

print("\n3. PERFORMANCE RANKINGS (1 = Best):")
for metric in metrics_to_compare:
    print(f"\n{metric}:")
    metric_ranks = ranking_df[ranking_df['Metric'] == metric].sort_values('Rank')
    for _, row in metric_ranks.iterrows():
        print(f"  {row['Benchmarking Group']}: Rank {int(row['Rank'])} (Value: {row['Actual Value']:.1f})")

print("\n" + "="*70)
print("CONCLUSION")
print("="*70)
print("• Comprehensive multi-metric analysis provides holistic view of energy performance")
print("• Radar charts enable cross-metric comparison despite different scales")
print("• Box plot analysis reveals distribution patterns and outliers within groups")
print("• Ranking system identifies leaders and laggards across different metrics")
print("• Full dataset analysis ensures robust and representative insights")

pip install ydata-profiling

import pandas as pd
    from ydata_profiling import ProfileReport

    # Load your dataset (replace 'your_data.csv' with your file path)
    df = pd.read_csv('final_padv.csv')

        # Create the profile report object
    profile = ProfileReport(df, title="Pandas Profiling Report")

    # Save the report to an HTML file
    profile.to_file("your_report.html")

profile.to_notebook_iframe()